name: Sync

on:
  schedule:
    - cron: '5 15 * * 5' # at 05:05am on Saturday NZST
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x]

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v7

      - name: 🔢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⏬ Install
        run: |
          npm ci

      - name: 🌏 Download planet file extract
        run: |
          yarn download-planet
        env:
          OSM_AUTH: ${{ secrets.OSM_AUTH }}

      - name: 🥝 Download LINZ csv file
        run: |
          yarn download-linz
        env:
          OPEN_ADDRESSES_USERNAME: ${{ secrets.OPEN_ADDRESSES_USERNAME }}
          OPEN_ADDRESSES_PASSWORD: ${{ secrets.OPEN_ADDRESSES_PASSWORD }}

      - name: ⏩ Download list of addresses to ignore
        run: |
          yarn preprocess0

      - name: 🚚 Preprocess the .osm.pbf file
        run: |
          yarn preprocess1

      - name: 🚚 Preprocess the .csv file
        run: |
          yarn preprocess2

      - name: 🚚 Creates stacks from LINZ data
        run: |
          yarn preprocess3

      - name: 🔁 Conflate LINZ data with OSM
        run: |
          yarn conflate

      - name: 🏡 Generate geojson and reports
        run: |
          yarn action
        env:
          MAX_ITEMS_PER_DATASET: ${{ secrets.MAX_ITEMS_PER_DATASET }}

      - name: ⛅ Upload dist folder
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
